version: "3.8"
services:
  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
